# config/routes.yaml
home:
  path: /{_locale}
  controller: App\Controller\DefaultController::home
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
contact:
  path: /{_locale}/contact
  controller: App\Controller\ContactController::contact
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
panier:
  path: /{_locale}/panier
  controller: App\Controller\PanierController::panier
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr


boutique:
  path: /{_locale}/boutique
  controller: App\Controller\BoutiqueController::boutique
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

compte:
  path: /{_locale}/compte
  controller: App\Controller\CompteController::compte
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

commandes:
  path: /{_locale}/commandes
  controller: App\Controller\CommandesController::commandes
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

produits:
  path: /{_locale}/produits/{idCategorie}
  controller: App\Controller\BoutiqueController::produits
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

ajouterProduit:
  path: /{_locale}/ajouterProduit/{idProduit}
  controller: App\Controller\PanierController::ajouterProduit
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

panierAddQuantite:
  path: /{_locale}/produitQuantite/{idProduit}
  controller: App\Controller\PanierController::panierAddQuantite
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

panierRemoveQuantite:
  path: /{_locale}/produitRemoveQuantite/{idProduit}
  controller: App\Controller\PanierController::panierRemoveQuantite
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

panierRemoveProduit:
  path: /{_locale}/produitRemove/{idProduit}
  controller: App\Controller\PanierController::panierRemoveProduit
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
nbProduits:
  path: /{_locale}/nbProduits
  controller: App\Controller\DefaultController::nbProduits
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

userAccueil:
  path: /{_locale}/user_accueil
  controller: App\Controller\UserController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

passerCommande:
  path: /{_locale}/passerCommande
  controller: App\Controller\PanierController::passerCommande
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

login:
  path: /{_locale}/login
  controller: App\Controller\SecuriteController::login
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
logout:
  path: /{_locale}/logout
  controller: App\Controller\SecuriteController::logout
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr
register:
  path: /{_locale}/register
  controller: App\Controller\SecuriteController::register
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

backoffice:
  path: /{_locale}/backoffice
  controller: App\Controller\BackofficeController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

createCategory:
  path: /{_locale}/createCategory
  controller: App\Controller\BackofficeController::createCategory
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

createProduct:
    path: /{_locale}/createProduct
    controller: App\Controller\BackofficeController::createProduct
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

gererCommandes:
  path: /{_locale}/gererCommandes
  controller: App\Controller\BackofficeController::gererCommandes
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

cloreCommande:
  path: /{_locale}/cloreCommande/{id}
  controller: App\Controller\CommandesController::cloreCommande
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

supprimerCommande:
  path: /{_locale}/supprimerCommande/{id}
  controller: App\Controller\CommandesController::supprimerCommande
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

rechercheProduit:
  path: /{_locale}/rechercheProduit
  controller: App\Controller\BoutiqueController::rechercheProduit
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr